# Generated by Django 4.1.2 on 2022-11-30 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_blogpost_slug_alter_blogpost_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='auther',
            new_name='author',
        ),
    ]
